import React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import ContractTypeSelect from "./ContractTypeSelect";

const formSchema = z.object({
  client: z.string().min(1, "Le nom du client est requis"),
  type: z.string().min(1, "Le type de contrat est requis"),
  montant: z.number().min(0, "Le montant doit être positif"),
  currency: z.string().min(1, "La devise est requise"),
  garantie: z.string().min(1, "La garantie est requise"),
  agence: z.string().min(1, "L'agence est requise"),
  description: z.string().optional(),
});

type FormData = z.infer<typeof formSchema>;

interface CreateContractDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onContractCreated: () => void;
}

const CreateContractDialog = ({ open, onOpenChange, onContractCreated }: CreateContractDialogProps) => {
  const { toast } = useToast();
  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      client: "",
      type: "",
      montant: 0,
      currency: "EUR",
      garantie: "",
      agence: "",
      description: "",
    },
  });

  const onSubmit = async (data: FormData) => {
    console.log("Submitting contract data:", data);
    
    try {
      const contractData = {
        client: data.client,
        type: data.type,
        montant: data.montant,
        currency: data.currency,
        garantie: data.garantie,
        agence: data.agence,
        description: data.description || "",
        reference_decision: "", // This will be auto-generated by the trigger
      };

      console.log("Contract data to insert:", contractData);

      const { data: insertedData, error } = await supabase
        .from("contracts")
        .insert(contractData)
        .select();

      if (error) {
        console.error("Supabase error:", error);
        throw error;
      }

      console.log("Contract created successfully:", insertedData);

      toast({
        title: "Contrat créé",
        description: "Le nouveau contrat a été créé avec succès.",
      });

      form.reset();
      onOpenChange(false);
      onContractCreated();
    } catch (error) {
      console.error("Error creating contract:", error);
      toast({
        title: "Erreur",
        description: "Une erreur s'est produite lors de la création du contrat.",
        variant: "destructive",
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Nouveau Contrat</DialogTitle>
          <DialogDescription>
            Créez un nouveau contrat de financement bancaire.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="client"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Client</FormLabel>
                  <FormControl>
                    <Input placeholder="Nom du client" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            {/* Use the extracted ContractTypeSelect component */}
            <FormField
              control={form.control}
              name="type"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Type de Contrat</FormLabel>
                  <FormControl>
                    <ContractTypeSelect value={field.value} onChange={field.onChange} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="grid grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="montant"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Montant</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder="0"
                        {...field}
                        onChange={(e) => field.onChange(parseFloat(e.target.value) || 0)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="currency"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Devise</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Devise" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="EUR">Euro (€)</SelectItem>
                        <SelectItem value="USD">Dollar ($)</SelectItem>
                        <SelectItem value="TND">Dinar Tunisien (TND)</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <FormField
              control={form.control}
              name="garantie"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Garantie</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Sélectionnez la garantie" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="hypotheque">Hypothèque</SelectItem>
                      <SelectItem value="caution">Caution</SelectItem>
                      <SelectItem value="nantissement">Nantissement</SelectItem>
                      <SelectItem value="gage">Gage</SelectItem>
                      <SelectItem value="aucune">Aucune</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="agence"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Agence</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Sélectionnez l'agence" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent className="max-h-60 overflow-y-auto">
                      <SelectItem value="agence_centrale_cun">Agence Centrale CUN</SelectItem>
                      <SelectItem value="la_marsa">La Marsa</SelectItem>
                      <SelectItem value="aouina">Aouina</SelectItem>
                      <SelectItem value="berges_du_lac_2">Les Berges du Lac 2</SelectItem>
                      <SelectItem value="petite_ariana">Petite Ariana</SelectItem>
                      <SelectItem value="ben_arous">Ben Arous</SelectItem>
                      <SelectItem value="denden">Denden</SelectItem>
                      <SelectItem value="ennasr">Ennasr</SelectItem>
                      <SelectItem value="kheireddine_pacha">Kheireddine Pacha</SelectItem>
                      <SelectItem value="bizerte">Bizerte</SelectItem>
                      <SelectItem value="nabeul">Nabeul</SelectItem>
                      <SelectItem value="nabeul_mrezga">Nabeul Mrezga</SelectItem>
                      <SelectItem value="sousse">Sousse</SelectItem>
                      <SelectItem value="monastir">Monastir</SelectItem>
                      <SelectItem value="sfax_bostene">Sfax Bostène</SelectItem>
                      <SelectItem value="sfax_gremda">Sfax Gremda</SelectItem>
                      <SelectItem value="sfax_route_gabes">Sfax Route de Gabès</SelectItem>
                      <SelectItem value="gabes">Gabès</SelectItem>
                      <SelectItem value="medenine">Médenine</SelectItem>
                      <SelectItem value="djerba">Djerba</SelectItem>
                      <SelectItem value="ras_jdir">Ras Jdir</SelectItem>
                      <SelectItem value="megrine">Mégrine</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description (optionnel)</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Détails supplémentaires..."
                      className="resize-none"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="submit">Créer le Contrat</Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
};

export default CreateContractDialog;
