// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqyuhztxmaawzzhdartp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeXVoenR4bWFhd3p6aGRhcnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTEyOTksImV4cCI6MjA2NTE2NzI5OX0.oIvbelJlh_LmcbVAdofVdABr5QXo2Tevz2Yyph-jeUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);